import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./components/CartContext";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <CartProvider><Navbar/>{children}</CartProvider>
      </body>
    </html>
  );
}



